### ISSUE TITLE
exception: Could not load type 'System.Runtime.Serialization.SerializationBinder'

### ISSUE THREAD

**Issue by liesauer** [edjCase/JsonRpc#60]
my code
```csharp
public void call(Context ctx, PhpString name, PhpArray args)
        {
            IList<object> toObjectList(PhpArray arr) {
                IList<object> datas = new List<object> {};
                foreach (KeyValuePair<IntStringKey, PhpValue> item in arr)
                {
                    if (item.Value.IsArray)
                    {
                        datas.Add(toObjectList(item.Value.ToArray()));
                    } else {
                        datas.Add(item.Value.ToString(ctx));
                    }
                }
                return datas;
            }
            IList<object> param = toObjectList(args);
            RpcResponse rsponse = _client.SendRequestWithListAsync(name.ToString(ctx), "", param).Result;
        }
```

```
发生异常: CLR/System.AggregateException
Exception thrown: 'System.AggregateException' in System.Private.CoreLib.dll: 'One or more errors occurred.'
 Inner exceptions found, see $exception in variables window for more details.
 Innermost exception 	 System.TypeLoadException : Could not load type 'System.Runtime.Serialization.SerializationBinder' from assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
   at Newtonsoft.Json.JsonSerializer..ctor()
   at Newtonsoft.Json.JsonSerializer.Create(JsonSerializerSettings settings)
   at EdjCase.JsonRpc.Client.DefaultRequestJsonSerializer.SerializeValue(Object value, JsonTextWriter jsonWriter)
   at EdjCase.JsonRpc.Client.DefaultRequestJsonSerializer.SerializeRequest(RpcRequest request, JsonTextWriter jsonWriter)
   at EdjCase.JsonRpc.Client.DefaultRequestJsonSerializer.SerializeInternal(IEnumerable`1 requests, Boolean isBulkRequest)
   at EdjCase.JsonRpc.Client.RpcClient.<SendAsync>d__20.MoveNext()
```

**Comment by liesauer** [comment]
@Gekctek is it so weird, i create a testcase which codes are completely same as my project, but it works fine! i am checking my project to find out whether is my project problem or not.

**Comment by liesauer** [comment]
@Gekctek i find the problem, my project reference one of my nuget pacage which was built by vs for mac in my office, and vs for mac package all the dlls into nuget package by default, including `System.Runtime.Serialization.Formatters`, so my project use `System.Runtime.Serialization.Formatters` which is insided my package, not the netcore one.
![1](https://user-images.githubusercontent.com/8676741/44345743-bf042580-a4c6-11e8-81fe-1185ac2e21ea.png)
![2](https://user-images.githubusercontent.com/8676741/44345745-bf042580-a4c6-11e8-82bc-c98863b8a52c.png)
