### ISSUE TITLE
Incompatibility with ASP.NET Core 3.0

### ISSUE THREAD

**Issue by BigDaddy1337** [edjCase/JsonRpc#68]
Hi, after add 

```
            services.AddJsonRpc().WithOptions(options =>
            {
                options.ShowServerExceptions = false;
                options.JsonSerializerSettings = new JsonSerializerSettings
                {
                    ContractResolver = new SnakeCasePropertyNamesContractResolver(),
                    NullValueHandling = NullValueHandling.Ignore,
                    Formatting = Formatting.Indented,
                    DefaultValueHandling = DefaultValueHandling.Include
                };
            });
```
to `ConfigureServices` -  app throws exception on start
```
Unhandled exception. System.MissingMethodException: Method not found: 'Microsoft.Extensions.DependencyInjection.IServiceCollection Microsoft.Extensions.DependencyInjection.AuthorizationServiceCollectionExtensions.AddAuthorization(Microsoft.Extensions.Depend
encyInjection.IServiceCollection)'.
   at Microsoft.AspNetCore.Builder.BuilderExtensions.AddJsonRpc(IServiceCollection serviceCollection)
   at TestJsonRpc.Startup.ConfigureServices(IServiceCollection services) in C:\Repository\TestJsonRpc\TestJsonRpc\Startup.cs:line 32
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass12_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at TestJsonRpc.Program.Main(String[] args) in C:\Repository\TestJsonRpc\TestJsonRpc\Program.cs:line 16

```
settings:

```
<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>netcoreapp3.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="EdjCase.JsonRpc.Router" Version="3.0.1" />
    </ItemGroup>

</Project>
```

**Comment by Gekctek** [comment]
related: https://github.com/aspnet/Announcements/issues/386

**Comment by Gekctek** [comment]
Putting up Nuget package 3.1.0 now

**Comment by BigDaddy1337** [comment]
Thanks for the quick update, but there is still an exception:

```
fail: EdjCase.JsonRpc.Router.RpcHttpRouter[0]
      Unknown exception occurred when trying to process Rpc request. Marking route unhandled
      System.InvalidOperationException: Synchronous operations are disallowed. Call WriteAsync or set AllowSynchronousIO to true instead.
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseStream.Write(Byte[] buffer, Int32 offset, Int32 count)
         at System.IO.Compression.DeflateStream.WriteDeflaterOutput()
         at System.IO.Compression.DeflateStream.WriteCore(ReadOnlySpan`1 buffer)
         at System.IO.Compression.DeflateStream.Write(Byte[] array, Int32 offset, Int32 count)
         at System.IO.Compression.GZipStream.Write(Byte[] array, Int32 offset, Int32 count)
         at System.IO.MemoryStream.CopyTo(Stream destination, Int32 bufferSize)
         at System.IO.Stream.CopyTo(Stream destination)
         at EdjCase.JsonRpc.Core.Tools.DefaultStreamCompressor.Compress(Stream inputStream, Stream outputStream, CompressionType compressionType)
         at EdjCase.JsonRpc.Router.RpcHttpRouter.RouteAsync(RouteContext context)
System.InvalidOperationException: Synchronous operations are disallowed. Call WriteAsync or set AllowSynchronousIO to true instead.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Compression.DeflateStream.WriteDeflaterOutput()
   at System.IO.Compression.DeflateStream.WriteCore(ReadOnlySpan`1 buffer)
   at System.IO.Compression.DeflateStream.Write(Byte[] array, Int32 offset, Int32 count)
   at System.IO.Compression.GZipStream.Write(Byte[] array, Int32 offset, Int32 count)
   at System.IO.MemoryStream.CopyTo(Stream destination, Int32 bufferSize)
   at System.IO.Stream.CopyTo(Stream destination)
   at EdjCase.JsonRpc.Core.Tools.DefaultStreamCompressor.Compress(Stream inputStream, Stream outputStream, CompressionType compressionType)
   at EdjCase.JsonRpc.Router.RpcHttpRouter.RouteAsync(RouteContext context)

```

related https://github.com/aspnet/AspNetCore/issues/7644

@Gekctek
