### ISSUE TITLE
Incompatibility with ASP.NET Core 3.0 (2)

### ISSUE THREAD

**Issue by BigDaddy1337** [edjCase/JsonRpc#69]
Thanks for the [quick update](https://github.com/edjCase/JsonRpc/issues/68), but there is still an exception:

```
fail: EdjCase.JsonRpc.Router.RpcHttpRouter[0]
      Unknown exception occurred when trying to process Rpc request. Marking route unhandled
      System.InvalidOperationException: Synchronous operations are disallowed. Call WriteAsync or set AllowSynchronousIO to true instead.
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseStream.Write(Byte[] buffer, Int32 offset, Int32 count)
         at System.IO.Compression.DeflateStream.WriteDeflaterOutput()
         at System.IO.Compression.DeflateStream.WriteCore(ReadOnlySpan`1 buffer)
         at System.IO.Compression.DeflateStream.Write(Byte[] array, Int32 offset, Int32 count)
         at System.IO.Compression.GZipStream.Write(Byte[] array, Int32 offset, Int32 count)
         at System.IO.MemoryStream.CopyTo(Stream destination, Int32 bufferSize)
         at System.IO.Stream.CopyTo(Stream destination)
         at EdjCase.JsonRpc.Core.Tools.DefaultStreamCompressor.Compress(Stream inputStream, Stream outputStream, CompressionType compressionType)
         at EdjCase.JsonRpc.Router.RpcHttpRouter.RouteAsync(RouteContext context)
System.InvalidOperationException: Synchronous operations are disallowed. Call WriteAsync or set AllowSynchronousIO to true instead.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Compression.DeflateStream.WriteDeflaterOutput()
   at System.IO.Compression.DeflateStream.WriteCore(ReadOnlySpan`1 buffer)
   at System.IO.Compression.DeflateStream.Write(Byte[] array, Int32 offset, Int32 count)
   at System.IO.Compression.GZipStream.Write(Byte[] array, Int32 offset, Int32 count)
   at System.IO.MemoryStream.CopyTo(Stream destination, Int32 bufferSize)
   at System.IO.Stream.CopyTo(Stream destination)
   at EdjCase.JsonRpc.Core.Tools.DefaultStreamCompressor.Compress(Stream inputStream, Stream outputStream, CompressionType compressionType)
   at EdjCase.JsonRpc.Router.RpcHttpRouter.RouteAsync(RouteContext context)

```

related https://github.com/aspnet/AspNetCore/issues/7644

**Comment by Gekctek** [comment]
Im not sure I can fix this without making a breaking change to the compression interface.

I am testing the next version of the library which is a big rewrite for performance and ease of use. This is designed around .netcore 3 and already has this fixed. So we may just have to wait till then unless you see a good alternative.

I did find a workaround for the kestrel server: https://stackoverflow.com/questions/47735133/asp-net-core-synchronous-operations-are-disallowed-call-writeasync-or-set-all 
Hopefully that can help for now.

**Comment by Gekctek** [comment]
https://www.nuget.org/packages/EdjCase.JsonRpc.Router/4.0.0-beta.1

I just published the new version if you want to try it out (may take 30-60 min to show up on nuget)
